### Load in NumPy (remeber to pip install numpy first)

In [7]:
import numpy as np

### The Basics

In [21]:
a = np.array([1,2,3],dtype = 'int16')
print(a)

[1 2 3]


In [10]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
# Get Dimension
b.ndim

2

In [30]:
# Get Shape
b.shape

(2, 3)

In [22]:
# Get Type
a.dtype

dtype('int16')

In [23]:
# Get Size 
a.itemsize

2

In [29]:
# Get total size
# a.size * a.itemsize
a.nbytes

6

In [31]:
# Get number of elements 
b.size

6

### Accessing/Changing specific elements, rows, columns, etc

In [5]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
# Get a specific element [r,c]
print(a[1,5])

13


In [10]:
# Get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [12]:
# Get a specific column 
print(a[:,1])

[2 9]


In [13]:
# Getting a bit more fancy [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [16]:
a[1,5] =20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
